// ── CONFIG ──────────────────────────────────────────────────
const SUPABASE_URL      = 'https://xmondkilgkesaqaspmfq.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhtb25ka2lsZ2tlc2FxYXNwbWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE2NjU2NjIsImV4cCI6MjA5NzI0MTY2Mn0.-W9hrn4Ts_CbceZq4HEVoqdTjt4oBPqFtXsmvfRZEwA';
const GAS_URL = 'https://script.google.com/macros/s/AKfycbywOPXKEYBeM7KaAUrdPaExW0EWAHH3tLVg0gfhm2--iavwWuuIGiEOkTh7R5EYqyLd/exec';
const _sb = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// Cliente aparte, de solo lectura, directo al Supabase de Zaiko (inventario
// oficial) -- SOLO para consultas (catalogo, busqueda en vivo). La anon key
// es publica por diseño (igual que la de Biblioteca arriba), protegida por
// RLS del lado de Zaiko, no por secreto -- es la misma que ya vive expuesta
// en el propio codigo cliente de Zaiko. Pasar por aqui en vez de por Apps
// Script evita el round-trip de GAS (1-4s típico) en cada busqueda/pagina
// del catalogo. Los movimientos que ESCRIBEN en Zaiko (salida, devolucion,
// conteo, prestamo de libro) siguen yendo por gasCall — RLS de Zaiko no deja
// escribir con la anon key, solo con el JWT de servicio que vive en Apps
// Script (Script Properties, nunca en el navegador).
const ZAIKO_SUPABASE_URL      = 'https://uimmarckhwnsrlkiexgs.supabase.co';
const ZAIKO_SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpbW1hcmNraHduc3Jsa2lleGdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA2MDQ1OTUsImV4cCI6MjA5NjE4MDU5NX0.Qk7gQ_RYKoNXQHJx9MkNA86Wts6sSp-fUWYkfAFxQwU';
const _sbZaiko = supabase.createClient(ZAIKO_SUPABASE_URL, ZAIKO_SUPABASE_ANON_KEY);

const _hoy = new Date();
const MESES = ['Enero','Febrero','Marzo','Abril','Mayo','Junio',
               'Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];

const PROFS_LISTA = ['ACERO CELIS GERSON DANOVIS','ACEROS ORTEGA YOHANA MARCELA','ACEVEDO RINCON FRAN JARVEY','ALARCON PLATA LIZETH DAYANNA','ALVAREZ RENGIFO PAULA LILIANA','ARGUELLO GORDILLO LEYDI ESTRELLA','BALLESTEROS GALVIS LIZETH O','BARRAGAN GOMEZ DANIELA','BOLAÑOS SAENZ FRANCIS ANDREA','BOTERO CARRILLO DIANA MARCELA','CABEZA HERNANDEZ MARIA ALEXANDRA','CABEZA NIÑO DANIELA','CABRA LAIDEO CESAR','CALA MORA ANDERSON DAVID','CALDERON DIAZ EMMI MARLEIBI','CAMARGO ZULETA JOHAN DAVID','CAPACHO MOGOLLÓN EDGAR ORIOL','CARMONA MATTOS LUZ ELENA','CARO RINCON ALEYDA','CARRERO SILVA ANDRES FELIPE','CASTELLANOS CUEVAS NAZLY NAYIBE','CASTILLO OLARTE VALERIE','CASTRO MORENO MARIA ANGELICA','CELEMIN SANCHEZ MONICA ANDREINA','CELYS CACERES LUZ MILA','DIAZ DIAZ HELGA YOHANNA','DUARTE ARROYO LEIDY CAROLINA','ESTEVEZ ISMAEL','ESTUPIÑAN MANTILLA WILSON E','FIGUEREDO PRADA LAURA LUCIA','FLOREZ MEDRANO LAURA NATHALIA','FORERO NIÑO IRMA LUCIA','GARCIA GOMEZ JHOHAN SEBASTIAN','GARZON OJEDA MARIA FERNANDA','GONZALEZ MALDONADO GUILLERMO','GONZALEZ MALDONADO HERNANDO','GONZALEZ MARTINEZ MICHAEL SANTIAGO','GONZALEZ MEJIA LIBIAM MARITZA','HERNANDEZ CALDERON HERMA JULIETH','HERNANDEZ ROJAS EYLEN','HERNANDEZ ROJAS LESLY JULIANA','JAGUA ZAMORA SERGIO ALBERTO','JAIMES MEDINA GENNY PATRICIA','JAIMES MEDINA SANDRA MERCEDES','JIMENEZ ACEVEDO EIMY KATHERINE','MARTINEZ ACEVEDO A SANTIAGO','MATEUS GONZALEZ SERGIO','MEJIA DE GONZALEZ EVELIA','MEJIA GARCIA RUBEN YAIR','MENDOZA ACEVEDO LAURA MARCELA','MONOGA MEJIA GLORIA JANETH','MONOGA MEJIA SONIA ROCIO','MONTAÑA CHAPARRO MARCO ANTONIO','MURILLO PINZON LUZ ALBA','ORTIZ GAMBOA JEISON MIGUEL','ORTIZ GOMEZ JOHANA EMILSE','ORTIZ TORRES YOLIMA','OTERO RAMIREZ JAZBEYDY','OTERO RODRIGUEZ SANDRA ROCIO','PARRA CARRILLO LUIS GONZALO','PATIÑO CUBIDES YUDI ALEJANDRA','PEINADO ORTIZ CLAUDIA PATRICIA','PEREZ QUINTERO SANDRA MARCELA','PEREZ SILVA SARAY DAYANNA','PINEDA SANDRA MARIA','PINTO ORTEGA YEANMARA','PINTO VARGAS YADDY ZULAY','QUIJANO FAJARDO LEYDI TATIANA','RAMIREZ BADILLO JENNY MARITZA','RICO VILLARREAL BIANY','RIOS OSSES RICARDO','RIVEROS MENDOZA CLAUDIA M','RODRIGUEZ LOZANO YULY ANDREA','ROMERO DAMARIS','ROMERO TRILLOS NICOLE S','RONDON NIÑO SONIA','RONDON URIBE FAVIO','RUEDA GONZALEZ CLAUDIA MARITZA','RUIZ MARIN YULY ANDREA','SAAVEDRA SANTAMARIA LUDWING','SANDOVAL LARROTTA SANDRA M','SANDOVAL SANDOVAL YANID SIRLEY','SANMIGUEL GARCIA ANGIE K','SILVA ROJAS HERMAN ALBERTO','SOLANO SERRANO LINA MARIA','TARAZONA BARON RUBEN DARIO','TELLO SUAREZ SANDRA CAROLINA','VALENCIA PEREZ JORGE LUIS','VARGAS HERNANDEZ JULIAN F','VEGA GONZALEZ MAYRA ALEJANDRA','VILLAMIZAR PEREZ CANDY VIVIANA','VILLAMIZAR TRILLOS DIEGO A','YEPEZ LUCENA YADIRA'];
